{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kixo",
    "module": "kixo-android-sdk",
    "version": "0.1.0-alpha6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.0-alpha6.aar",
          "url": "kixo-android-sdk-0.1.0-alpha6.aar",
          "size": 849949,
          "sha512": "bb4cc4e2234ddd7f7e7b93e19fac60e514dc11242af94aee9285ef9fcc92b74e14709b9bb814e86e212539d0dae0c29a5a24f265fa641cf90b6ad8ac03e87512",
          "sha256": "7dc2329a11ab0bd7e605071c55d13eb7798a206dbfee9be250116a102968afae",
          "sha1": "1a187ee7668cc7999579c3894a68691119af5949",
          "md5": "23820b57e19457a79f2056d01d702b36"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.0-alpha6.aar",
          "url": "kixo-android-sdk-0.1.0-alpha6.aar",
          "size": 849949,
          "sha512": "bb4cc4e2234ddd7f7e7b93e19fac60e514dc11242af94aee9285ef9fcc92b74e14709b9bb814e86e212539d0dae0c29a5a24f265fa641cf90b6ad8ac03e87512",
          "sha256": "7dc2329a11ab0bd7e605071c55d13eb7798a206dbfee9be250116a102968afae",
          "sha1": "1a187ee7668cc7999579c3894a68691119af5949",
          "md5": "23820b57e19457a79f2056d01d702b36"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kixo-android-sdk-0.1.0-alpha6-sources.jar",
          "url": "kixo-android-sdk-0.1.0-alpha6-sources.jar",
          "size": 1074606,
          "sha512": "bd52b38a078bb8cf9d9ccc4f4aa8f3845055303b3481f87e83d446eae1e79581941ed07b2da7f36ddf90ff727b4bec6a814e99736a8d1069398fa6e1130abb97",
          "sha256": "401706f531f6245a47d93224105109700945e0855dc7233609a83e816fba7274",
          "sha1": "deeb309546f2c9721c1ccedc458324337fb105f7",
          "md5": "dbc0ba8529b4ce6b9bd97391a0dbb7dc"
        }
      ]
    }
  ]
}
