{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kixo",
    "module": "kixo-android-sdk",
    "version": "0.1.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.18.aar",
          "url": "kixo-android-sdk-0.1.18.aar",
          "size": 1868631,
          "sha512": "568f845034fb278c256bd78eb186ce5d3897dface16aeed484d8e7d9b777246df022e1571fe1a30f54fbfb7b9f2b44ef6452b710eb687a60a9fbfce8dc70fe00",
          "sha256": "50afd2da2f2a14a1269de09ebd56526a753f6e895c0aaec2afbe92b0862b8c28",
          "sha1": "792830f9dc219c8b9e8ebbf7894ddcfaea80f629",
          "md5": "b2016dcd122da6a0b3571a7434f12d29"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.18.aar",
          "url": "kixo-android-sdk-0.1.18.aar",
          "size": 1868631,
          "sha512": "568f845034fb278c256bd78eb186ce5d3897dface16aeed484d8e7d9b777246df022e1571fe1a30f54fbfb7b9f2b44ef6452b710eb687a60a9fbfce8dc70fe00",
          "sha256": "50afd2da2f2a14a1269de09ebd56526a753f6e895c0aaec2afbe92b0862b8c28",
          "sha1": "792830f9dc219c8b9e8ebbf7894ddcfaea80f629",
          "md5": "b2016dcd122da6a0b3571a7434f12d29"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kixo-android-sdk-0.1.18-sources.jar",
          "url": "kixo-android-sdk-0.1.18-sources.jar",
          "size": 1822639,
          "sha512": "1054614c30387eaf1d638bad8928a36e815dac24fea4eb565857f6d8743f5c8666aef53cc84e51d3c4ac35adb77b1a2679932b1b9082dee98f9c00f5c8b7f808",
          "sha256": "f373a886e011426e7157cd9b1c97b7cb8237e868a5630aaa07939e775c5558b7",
          "sha1": "4f3ec3fc049ed59522d243a7770654d509be3d2c",
          "md5": "0a9350aaf07406ba05aba2286c46dbf3"
        }
      ]
    }
  ]
}
