{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kixo",
    "module": "kixo-android-sdk",
    "version": "0.1.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.17.aar",
          "url": "kixo-android-sdk-0.1.17.aar",
          "size": 1901556,
          "sha512": "08a7dacdb479dc10cac9c26fee47c73a9e468100d05734bd26cd3a713809774722645a68bfabb9875ce9ca4d7b85fa86236837319b73978ed5efbe926979cf2a",
          "sha256": "4771eac335f931a6e3e486b1431e510215dbbff82b977f806a6343c6dad74ef3",
          "sha1": "18b6d69131f9f7b1b2d7b5006905aaa0f671c164",
          "md5": "4cb105bd21b8840a956a8cae1f3a7de5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.17.aar",
          "url": "kixo-android-sdk-0.1.17.aar",
          "size": 1901556,
          "sha512": "08a7dacdb479dc10cac9c26fee47c73a9e468100d05734bd26cd3a713809774722645a68bfabb9875ce9ca4d7b85fa86236837319b73978ed5efbe926979cf2a",
          "sha256": "4771eac335f931a6e3e486b1431e510215dbbff82b977f806a6343c6dad74ef3",
          "sha1": "18b6d69131f9f7b1b2d7b5006905aaa0f671c164",
          "md5": "4cb105bd21b8840a956a8cae1f3a7de5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kixo-android-sdk-0.1.17-sources.jar",
          "url": "kixo-android-sdk-0.1.17-sources.jar",
          "size": 1877101,
          "sha512": "9f0892b5ee2539bdeb8a6e444f6e75e7272296e551f88819ea4a7f7c448c81792d7a0838c70f24108a69f323360af36b6914548b8b3c54809470a2ac269720e0",
          "sha256": "e63cf34fb91b25a8af4d22cdd058f3566b90280127a051d15b490a2b8e30fbb0",
          "sha1": "d63c1b2e84a4e2809a17de250db51872e059930f",
          "md5": "716c3922242b4648c961af020025f91f"
        }
      ]
    }
  ]
}
