{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kixo",
    "module": "kixo-android-sdk",
    "version": "0.1.0-alpha7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.0-alpha7.aar",
          "url": "kixo-android-sdk-0.1.0-alpha7.aar",
          "size": 871275,
          "sha512": "a00ab5d5675690e330f9754499f2f3ae71071fad34904be9b5ceb1ac06f7571ec8f01e3c30b41b0fc1671b27a38216f6fd7ffc382e0434ff4eed65f317db75ed",
          "sha256": "b7cd4dcc05c97450d502bf6efc028761cc99a1447f8418628025ddad61af7aa0",
          "sha1": "cc73d82a03692287a440ca4adf1eb5d0dcafb755",
          "md5": "d3ebd2be07e228824efec44971736ce4"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.0-alpha7.aar",
          "url": "kixo-android-sdk-0.1.0-alpha7.aar",
          "size": 871275,
          "sha512": "a00ab5d5675690e330f9754499f2f3ae71071fad34904be9b5ceb1ac06f7571ec8f01e3c30b41b0fc1671b27a38216f6fd7ffc382e0434ff4eed65f317db75ed",
          "sha256": "b7cd4dcc05c97450d502bf6efc028761cc99a1447f8418628025ddad61af7aa0",
          "sha1": "cc73d82a03692287a440ca4adf1eb5d0dcafb755",
          "md5": "d3ebd2be07e228824efec44971736ce4"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kixo-android-sdk-0.1.0-alpha7-sources.jar",
          "url": "kixo-android-sdk-0.1.0-alpha7-sources.jar",
          "size": 1083387,
          "sha512": "bb0ba7f7a226e9e1617ad6e309b31b6f6e2e4ea96fe0a54d61799dbaca5dc5eab7d4e4f271edc4adf25e3604686e082436d313bc41e9fa1d71ceeb85b22369ce",
          "sha256": "87ece3ee9e23974a351c176d5bd5c60adee49b6742127e1a53534c23fefea80b",
          "sha1": "86b4532b60ccd04600373b922dfd9b81ea3f28ba",
          "md5": "e75d210e8a0178cd257b88da578fa05f"
        }
      ]
    }
  ]
}
