{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kixo",
    "module": "kixo-android-sdk",
    "version": "0.1.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.11.aar",
          "url": "kixo-android-sdk-0.1.11.aar",
          "size": 1168919,
          "sha512": "ec6d1950d5a2a821bc6c2685d2b9f0bbccc1b1310b926596fc3cfc37624b3140762bf2af902028f565dadc97aff1a99eac190c83b09a45531e734ca8cd1d4897",
          "sha256": "c44590c50a908c808479fe915e1131fef2b0cbf1727bfef8ceea77b60f4f33d9",
          "sha1": "29af87f2023a27ddcc2f7b9b36d8d4f9f028c4b7",
          "md5": "0222f27c9a64b47848df74e3103b708a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.11.aar",
          "url": "kixo-android-sdk-0.1.11.aar",
          "size": 1168919,
          "sha512": "ec6d1950d5a2a821bc6c2685d2b9f0bbccc1b1310b926596fc3cfc37624b3140762bf2af902028f565dadc97aff1a99eac190c83b09a45531e734ca8cd1d4897",
          "sha256": "c44590c50a908c808479fe915e1131fef2b0cbf1727bfef8ceea77b60f4f33d9",
          "sha1": "29af87f2023a27ddcc2f7b9b36d8d4f9f028c4b7",
          "md5": "0222f27c9a64b47848df74e3103b708a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kixo-android-sdk-0.1.11-sources.jar",
          "url": "kixo-android-sdk-0.1.11-sources.jar",
          "size": 1463563,
          "sha512": "d35bee13260290b2dce1c8fce81a6d0dae64ad980be9e9f67cb038efe361f7c0847c0538668329a791228b68daa954b05a9de6b809b34700335e0288c99d61a0",
          "sha256": "7ff2380a0fef221083f27f935ba7968256d93ca9b934e398b3bab77cc52eca7f",
          "sha1": "13eb0ed3834eb65ce89e2e0f005edd20c2e86147",
          "md5": "eab7cb4788063aa655a691975e0853fd"
        }
      ]
    }
  ]
}
