{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kixo",
    "module": "kixo-android-sdk",
    "version": "0.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.9.aar",
          "url": "kixo-android-sdk-0.1.9.aar",
          "size": 1152777,
          "sha512": "f4fac8b2a442667613028b1e5243f899e2a59c4ac0cea73f0341a7e5d873a57d5fdf2882d25d3b8b2de417fff627c2fbab63e22df9b2d1bdaee05680d808fa09",
          "sha256": "bf3eeb79821e500a0750a4dbe4e6e833c140bdb4c14b617839da6feb0407d8b5",
          "sha1": "22b0b6488fa846a7acad019deef83c6d4d7d098f",
          "md5": "9fd335d2f8c893b65c0c7d9c7d4550a5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.9.aar",
          "url": "kixo-android-sdk-0.1.9.aar",
          "size": 1152777,
          "sha512": "f4fac8b2a442667613028b1e5243f899e2a59c4ac0cea73f0341a7e5d873a57d5fdf2882d25d3b8b2de417fff627c2fbab63e22df9b2d1bdaee05680d808fa09",
          "sha256": "bf3eeb79821e500a0750a4dbe4e6e833c140bdb4c14b617839da6feb0407d8b5",
          "sha1": "22b0b6488fa846a7acad019deef83c6d4d7d098f",
          "md5": "9fd335d2f8c893b65c0c7d9c7d4550a5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kixo-android-sdk-0.1.9-sources.jar",
          "url": "kixo-android-sdk-0.1.9-sources.jar",
          "size": 1419796,
          "sha512": "6895929f42dad2273954c6550e19fca42f54971eff1ecf5c93a90bd1a82393171623e8eb1083ad487aa7c8e9ee769aee49fa43bfc6856f861d258637abbe0a45",
          "sha256": "b6cdaba743b8f8c64ae03a90c11d35ea595fb87e51bcccdee7e580222ade22eb",
          "sha1": "64b63a5a26600eb37954664ff4b8b9262c0b1185",
          "md5": "463d760e18995d878b43c984f1bc6cc4"
        }
      ]
    }
  ]
}
