{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kixo",
    "module": "kixo-android-sdk",
    "version": "0.1.0-alpha4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.0-alpha4.aar",
          "url": "kixo-android-sdk-0.1.0-alpha4.aar",
          "size": 864876,
          "sha512": "da90208619e5de56641c48bc8dc604c35500e627ca7b145a8fd16ffe5919c6d7449a8954c94633ec0fbf8e7d2dbcea3d830681693c78614b2a131fb49e0fb965",
          "sha256": "379981d42d4b81fc10356ddb3391dde8726c2f5cae67cc57b499d5d9e802b3d7",
          "sha1": "27eb7713f6c12e7484d150284f9c9d853d0c423c",
          "md5": "8091edfde4674823d0d6185418c8fe89"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.0-alpha4.aar",
          "url": "kixo-android-sdk-0.1.0-alpha4.aar",
          "size": 864876,
          "sha512": "da90208619e5de56641c48bc8dc604c35500e627ca7b145a8fd16ffe5919c6d7449a8954c94633ec0fbf8e7d2dbcea3d830681693c78614b2a131fb49e0fb965",
          "sha256": "379981d42d4b81fc10356ddb3391dde8726c2f5cae67cc57b499d5d9e802b3d7",
          "sha1": "27eb7713f6c12e7484d150284f9c9d853d0c423c",
          "md5": "8091edfde4674823d0d6185418c8fe89"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kixo-android-sdk-0.1.0-alpha4-sources.jar",
          "url": "kixo-android-sdk-0.1.0-alpha4-sources.jar",
          "size": 1080891,
          "sha512": "30e578cafc352c6b1f78bf8df77fe3996bb0079d836a2022027175ece0cc123e1e0b2c871e1c2f4026ec8b83b9eaf9115ab2f81a6525836068068575da1b0281",
          "sha256": "aba1837cab59dd2662a33db92fd196d4c48fdef19bc9795042173ca39916fdd8",
          "sha1": "250f47f69d8e7aedd76ce9a8af5f4c20e367c8d8",
          "md5": "05a2a70e1bfcbe69509b1fd85e0f1494"
        }
      ]
    }
  ]
}
