{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kixo",
    "module": "kixo-android-sdk",
    "version": "0.1.0-alpha5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.0-alpha5.aar",
          "url": "kixo-android-sdk-0.1.0-alpha5.aar",
          "size": 865097,
          "sha512": "53150e08b6e4f554a43f4b76055e0164d5cf9be3a6ca3efe3a96a204ede95d2956504b95da7981939a37669abf41043e4077efe9b87c20abd1bf0d6302d7c98a",
          "sha256": "6b8df088c10d99b78518790aa82ca125dca1f36b532888b7bf6fbf7b65a5d70a",
          "sha1": "715a2bbcc085605fbb13d2fda79415d28cbe76bd",
          "md5": "2b8e42f9869b4c5c4894427332b06f4d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.0-alpha5.aar",
          "url": "kixo-android-sdk-0.1.0-alpha5.aar",
          "size": 865097,
          "sha512": "53150e08b6e4f554a43f4b76055e0164d5cf9be3a6ca3efe3a96a204ede95d2956504b95da7981939a37669abf41043e4077efe9b87c20abd1bf0d6302d7c98a",
          "sha256": "6b8df088c10d99b78518790aa82ca125dca1f36b532888b7bf6fbf7b65a5d70a",
          "sha1": "715a2bbcc085605fbb13d2fda79415d28cbe76bd",
          "md5": "2b8e42f9869b4c5c4894427332b06f4d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kixo-android-sdk-0.1.0-alpha5-sources.jar",
          "url": "kixo-android-sdk-0.1.0-alpha5-sources.jar",
          "size": 1081323,
          "sha512": "eab769ae6ecb14bed8e00c3c59c9f9c4ca3caf332df5de601d903df30ed179f9a690c062212d0dc620afc86324f2df4878ee8c3cf37f941dd5c6b6e38b05e272",
          "sha256": "cd4c93fa16278d49062a3c4a6f3d962f6da1ac594a5a1bf54e15b43305e07a07",
          "sha1": "38c6ee516eca0f012a5f313b5a476798907b323f",
          "md5": "b2267b719b04b3e0fd0c646545464b0f"
        }
      ]
    }
  ]
}
