{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kixo",
    "module": "kixo-android-sdk",
    "version": "0.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.10.aar",
          "url": "kixo-android-sdk-0.1.10.aar",
          "size": 1168420,
          "sha512": "59a4d1608cde406b37f523e43c217de0e6375955498a3a5294acc71cd320f89ddfad38220d98e8980a432d3e4e13036351403c49504115964789d0c3313b8012",
          "sha256": "d28f38b2118ae168057faba9355e21a7a280aad6552d5bdfd7f4a18b071be524",
          "sha1": "6038c41d6abfbf2a677fd63dc6a87affeb4df58d",
          "md5": "4e8336f590a9252e30e3db0b426eb18f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.10.aar",
          "url": "kixo-android-sdk-0.1.10.aar",
          "size": 1168420,
          "sha512": "59a4d1608cde406b37f523e43c217de0e6375955498a3a5294acc71cd320f89ddfad38220d98e8980a432d3e4e13036351403c49504115964789d0c3313b8012",
          "sha256": "d28f38b2118ae168057faba9355e21a7a280aad6552d5bdfd7f4a18b071be524",
          "sha1": "6038c41d6abfbf2a677fd63dc6a87affeb4df58d",
          "md5": "4e8336f590a9252e30e3db0b426eb18f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kixo-android-sdk-0.1.10-sources.jar",
          "url": "kixo-android-sdk-0.1.10-sources.jar",
          "size": 1461994,
          "sha512": "ebb73f93de31f987718654bbe078148147994e97aa2dc782df2a2d35232b68d1208f94f71bdc7cdd018c13d5a1452cd722551f646a5d94b3b5b860027dfd8952",
          "sha256": "5a7f336fd57ea66204a19f3d8809e3e9054828daabcdaa9d7bfad68ba835aa4e",
          "sha1": "fe330ec2a9ddb27e1679d1b78838bc1d1dc9fb5c",
          "md5": "db6709383849a69277aa6262c904a929"
        }
      ]
    }
  ]
}
