{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kixo",
    "module": "kixo-android-sdk",
    "version": "0.1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.20.aar",
          "url": "kixo-android-sdk-0.1.20.aar",
          "size": 1890505,
          "sha512": "c8192f78e092e2d92799deff6cfb2bd463bb8bb5473247eb85608cb2d0dcf42f3887ae4a90fcc3d62c81334c9d9866eba60ca5d9f50b583edf37852e133c008b",
          "sha256": "92da8fa88b5d29f312e8a17f31b6b04cf931f915c39ff61c86b01e3df0971100",
          "sha1": "e684dc8864ff1e7a5134a5729505df4b31250a84",
          "md5": "36d76b3fba29d6063db8689066a0425e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.20.aar",
          "url": "kixo-android-sdk-0.1.20.aar",
          "size": 1890505,
          "sha512": "c8192f78e092e2d92799deff6cfb2bd463bb8bb5473247eb85608cb2d0dcf42f3887ae4a90fcc3d62c81334c9d9866eba60ca5d9f50b583edf37852e133c008b",
          "sha256": "92da8fa88b5d29f312e8a17f31b6b04cf931f915c39ff61c86b01e3df0971100",
          "sha1": "e684dc8864ff1e7a5134a5729505df4b31250a84",
          "md5": "36d76b3fba29d6063db8689066a0425e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kixo-android-sdk-0.1.20-sources.jar",
          "url": "kixo-android-sdk-0.1.20-sources.jar",
          "size": 1841149,
          "sha512": "a3a2994b27bd3bbefa08759b9499e94712d047033cf17a1d0f50308ddef89804a8bacb02b2a8abe2a9f84393123d59ccebd10adea79c2c46b8ee8a343b0cb791",
          "sha256": "8534fc3d22d3e23993b5173361702cf08a2421d161ba6e03848cd7c88533588f",
          "sha1": "3268dc329aa016e5efef26cc6cc0ae99c91c1d8a",
          "md5": "d3e7d83b2b1ea6830ea06339fd4b0c0c"
        }
      ]
    }
  ]
}
