{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kixo",
    "module": "kixo-android-sdk",
    "version": "0.1.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.12.aar",
          "url": "kixo-android-sdk-0.1.12.aar",
          "size": 1210405,
          "sha512": "4649fa24da4498a626b2d51d09c489c1aec06857b31b8d3e72b43cfa407122304ff0b1e12e745c8487970ffa95483263ef36468454a08dc9668d88c8234f3e76",
          "sha256": "b78b4ff3775b75dd8c93c57b8514ef688fa6d5fc6b978ec12763694d54aa09c0",
          "sha1": "ff974fbe5f84a4b667aa8b570644edc4d65d776b",
          "md5": "d00536905754aacb0c7e8b6e4e06fd52"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.12.aar",
          "url": "kixo-android-sdk-0.1.12.aar",
          "size": 1210405,
          "sha512": "4649fa24da4498a626b2d51d09c489c1aec06857b31b8d3e72b43cfa407122304ff0b1e12e745c8487970ffa95483263ef36468454a08dc9668d88c8234f3e76",
          "sha256": "b78b4ff3775b75dd8c93c57b8514ef688fa6d5fc6b978ec12763694d54aa09c0",
          "sha1": "ff974fbe5f84a4b667aa8b570644edc4d65d776b",
          "md5": "d00536905754aacb0c7e8b6e4e06fd52"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kixo-android-sdk-0.1.12-sources.jar",
          "url": "kixo-android-sdk-0.1.12-sources.jar",
          "size": 1549876,
          "sha512": "4b146cb4afccbf156e848e57643f412a851af896f0d9ade39a5661223bbfa1a96ffe770b900b1e9a586dce022f94597c5048d1ed9be04db153be7f75b20030a4",
          "sha256": "7b5292cfca47c65d09c755ef3b472aa4e6ca7d7c7a2449be316f97a1e5179d3f",
          "sha1": "bb6ff4f05c1359d559fe1c1c5a48e64c2ed43acf",
          "md5": "8deec95f12bf9cc45e55ea65c25d09fb"
        }
      ]
    }
  ]
}
