{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kixo",
    "module": "kixo-android-sdk",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.3.aar",
          "url": "kixo-android-sdk-0.1.3.aar",
          "size": 907487,
          "sha512": "8758b5877c5083d527b19eb2234e57286819719d94e10d437cee17f406e0d5a03ccac6c19949f259e6be1d2a0ff6abcb9bc3cde0158a42dd73af345d60546662",
          "sha256": "0d7dd0a604813554d1968540c01b6bd1a7623b36059dbe3d3f910b889d7f847a",
          "sha1": "ee344dcf19e61e031e176282bcacaa7f98afdb0f",
          "md5": "5ba6f89d4d4822a8a95735723cf41eb5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "kixo-android-sdk-0.1.3.aar",
          "url": "kixo-android-sdk-0.1.3.aar",
          "size": 907487,
          "sha512": "8758b5877c5083d527b19eb2234e57286819719d94e10d437cee17f406e0d5a03ccac6c19949f259e6be1d2a0ff6abcb9bc3cde0158a42dd73af345d60546662",
          "sha256": "0d7dd0a604813554d1968540c01b6bd1a7623b36059dbe3d3f910b889d7f847a",
          "sha1": "ee344dcf19e61e031e176282bcacaa7f98afdb0f",
          "md5": "5ba6f89d4d4822a8a95735723cf41eb5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kixo-android-sdk-0.1.3-sources.jar",
          "url": "kixo-android-sdk-0.1.3-sources.jar",
          "size": 1166184,
          "sha512": "35b24510b59efec2db074354953dd6c6a8cadced1b7274ded380995a072e93a1cb5e3614bbe9e90307d7bd28418aa5429d294bf5cb4b8e70862bafbcfb932f1e",
          "sha256": "84f00424432458161c739dd278c655029edf758973aa4baa16fb02ea359a0ae1",
          "sha1": "d737ac91707ee042fc29e2dc7c6b3a9df97f8106",
          "md5": "8845c1c0a8986365df1d08f6bd4bd03c"
        }
      ]
    }
  ]
}
